### ISSUE TITLE
I code with my ass

### ISSUE THREAD

**Issue by rwellens** [flash-global/payment-common#32]
https://github.com/flash-global/payment-common/blob/1f6059cd839cb420a0720f78e855327be326a656/src/Entity/Payment.php#L163

@lvenier 😘

**Comment by lvenier** [comment]
what is not working ?

**Comment by rwellens** [comment]
NO https://travis-ci.org/flash-global/payment-common

Never use underscore to object property, you broke "toArray" and "Transform" method.

**Comment by lvenier** [comment]
do not write phinx migration with _ then... having a different name in class and table column is for me far worst than code styling !!!!

**Comment by rwellens** [comment]
you are just in bad faith, doctrine transform automatically camelCase to underscoring

**Comment by lvenier** [comment]
where do you see doctrine in phinx initial migration ?

**Comment by lvenier** [comment]
check my initial version :
https://github.com/flash-global/payment-common/commit/9aa88253cf5c2c6aea0c8d09988c5171912d1505#diff-6754ab4f242cef437296d96e92ce359a

But then I realize Opcoding and Flash does not know phinx and doctrine and apply something simple....

**Comment by rwellens** [comment]
Doctrine is used to manipulate entity, when your property has camels case doctrine automatically converts underscore to column name.

**Comment by lvenier** [comment]
pls explain this : 
https://github.com/flash-global/payment-api/blob/develop/migrations/20170523083854_init_payment_database.php
